high_threshold_Canny=0.8
initial_distortion_parameter=0.0
final_distortion_parameter=3.0
distance_point_line_max_hough=3.0
angle_point_orientation_max_difference=2.0
type_of_lens_distortion_model="div"
center_optimization="True"
undistorted_image_magnification=2
model_ldm=""

./video_correction_linux 1.AVI 1_defish.AVI $high_threshold_Canny $initial_distortion_parameter $final_distortion_parameter $distance_point_line_max_hough $angle_point_orientation_max_difference $type_of_lens_distortion_model $center_optimization $undistorted_image_magnification $model_ldm
./video_correction_linux 2.AVI 2_defish.AVI $high_threshold_Canny $initial_distortion_parameter $final_distortion_parameter $distance_point_line_max_hough $angle_point_orientation_max_difference $type_of_lens_distortion_model $center_optimization $undistorted_image_magnification $model_ldm
./video_correction_linux 3.AVI 3_defish.AVI $high_threshold_Canny $initial_distortion_parameter $final_distortion_parameter $distance_point_line_max_hough $angle_point_orientation_max_difference $type_of_lens_distortion_model $center_optimization $undistorted_image_magnification $model_ldm
./video_correction_linux 4.AVI 4_defish.AVI $high_threshold_Canny $initial_distortion_parameter $final_distortion_parameter $distance_point_line_max_hough $angle_point_orientation_max_difference $type_of_lens_distortion_model $center_optimization $undistorted_image_magnification $model_ldm
./video_correction_linux 5.AVI 5_defish.AVI $high_threshold_Canny $initial_distortion_parameter $final_distortion_parameter $distance_point_line_max_hough $angle_point_orientation_max_difference $type_of_lens_distortion_model $center_optimization $undistorted_image_magnification $model_ldm
./video_correction_linux 6.AVI 6_defish.AVI $high_threshold_Canny $initial_distortion_parameter $final_distortion_parameter $distance_point_line_max_hough $angle_point_orientation_max_difference $type_of_lens_distortion_model $center_optimization $undistorted_image_magnification $model_ldm
./video_correction_linux 7.AVI 7_defish.AVI $high_threshold_Canny $initial_distortion_parameter $final_distortion_parameter $distance_point_line_max_hough $angle_point_orientation_max_difference $type_of_lens_distortion_model $center_optimization $undistorted_image_magnification $model_ldm
